---
templates:
  - .gitconfig
  - .tmux.conf
  - .zsh/.zprofile
  - .zshenv

common_files:
  - .config/nvim
  - .gitconfig
  - .gitignore
  - .profile
  - .tmux.conf
  - .vim
  - .zsh
  - .zshenv

archlinux_files:
  - .Xresources
  - .Xresources.d
  - .config/i3
  - .config/rofi
  - .xinitrc

darwin_files:
  - .ideavimrc

vim_path: '{{ ansible_env.PWD }}/roles/dotfiles/files/.vim'
command_t_path: '{{ vim_path }}/pack/bundle/start/command-t'

git_user_name: '{{"baubler"}}'
git_user_email: '{{"29524087+baubler@users.noreply.github.com"}}'
