# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "k10temp" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/79e5dffc-32c9-42b1-91c8-aadf3b8014ee";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4EAC-6C7A";
      fsType = "vfat";
    };

    swapDevices = [ 
      {
        device = "/dev/disk/by-uuid/13bbc4a2-12c4-467f-a58b-97cbe313dcab";
      }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}

# # Do not modify this file!  It was generated by ‘nixos-generate-config’
# # and may be overwritten by future invocations.  Please make changes
# # to /etc/nixos/configuration.nix instead.
# { config, lib, pkgs, modulesPath, ... }:

# {
#   imports =
#     [ (modulesPath + "/installer/scan/not-detected.nix")
#     ];

#   boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "sd_mod" "rtsx_pci_sdmmc" ];
#   boot.initrd.kernelModules = [ ];
#   boot.kernelModules = [ ];
#   boot.extraModulePackages = [ ];

#   fileSystems."/" =
#     { device = "/dev/disk/by-uuid/55095c6f-6023-4529-aa73-8d54346048c4";
#       fsType = "ext4";
#     };

#   fileSystems."/boot" =
#     { device = "/dev/disk/by-uuid/FA2B-FAF5";
#       fsType = "vfat";
#     };

#   swapDevices =
#     [ { device = "/dev/disk/by-uuid/e29b676e-d004-4b5d-9fc3-1d52d49a7954"; }
#     ];

#   powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
#   hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
#   # high-resolution display
#   hardware.video.hidpi.enable = lib.mkDefault true;
# }
