---
name: "homelab"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3333:3000"
    environment:
      - GF_SERVER_HTTP_PORT=3333
    volumes:
      - grafana_storage:/var/lib/grafana
    network_mode: "host"

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./home/homarr/configs:/app/data/configs
      - ./home/homarr/icons:/app/public/icons
      - ./home/homarr/data:/data
    ports:
      - "7575:7575"
    network_mode: "host"

  flaresolverr:
    container_name: flaresolverr
    image: flaresolverr/flaresolverr
    restart: unless-stopped
    ports:
      - "8191:8191"
    network_mode: "host"
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    ports:
      - "8123:8123"
    network_mode: "host"
    volumes:
      - "./home/home-assistant:/config"
      - "/var/run/dbus:/var/run/dbus"
      - "/var/run/bluetooth:/var/run/bluetooth"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # sonoff zigbee dongle

  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GB
      - HARDCOVER_TOKEN=your_hardcover_api_key_here
      - NETWORK_SHARE_MODE=false
    volumes:
      - ./home/cwa/config:/config
      - ./home/cwa/ingest:/cwa-book-ingest
      - ./home/cwa/library:/calibre-library
      - ./home/cwa/plugins:/config/.config/calibre/plugins
    ports:
      - 8083:8083
    restart: unless-stopped
    network_mode: "host"

volumes:
  grafana_storage: {}
