#!/bin/bash
set -e

if [ -n "$1" ]; then
  ROLES="--tags $1"
fi

VENV_SETUP=lib/virtualenv/virtualenv.py
VENV=lib/env
VENV_ACTIVATE=$VENV/bin/activate
PIP=$VENV/bin/pip
ANSIBLE=$VENV/bin/ansible-playbook

python3 $VENV_SETUP $VENV &> /dev/stdout
source $VENV_ACTIVATE
$PIP install ansible &> /dev/stdout

HOST_OS=$(uname)
if [ "$HOST_OS" = 'Darwin' ]; then
  $ANSIBLE -i inventory darwin.yml $ROLES
elif [ "$HOST_OS" = 'Linux' ]; then
  $ANSIBLE -i inventory arch.yml $ROLES
else
  echo "Unknown host OS: $HOST_OS"
  exit 1
fi

trap - EXIT
