#!/bin/bash
set -e

if [ -n "$1" ]; then
  roles="--tags $1"
else
  roles="--tags dotfiles"  # sensible default
fi

# type ansible-playbook

# if [ $? -eq 0 ]; then
#   ansible=ansible-playbook
# else
venv=lib/env

python3 -m venv $venv

source $venv/bin/activate

$venv/bin/pip install --upgrade pip &> /dev/stdout

$venv/bin/pip install ansible &> /dev/stdout

ansible=$venv/bin/ansible-playbook
# fi

host_os=$(uname)

if [ "$host_os" = 'Darwin' ]; then
  cmd="$ansible -i inventory darwin.yml $roles"
elif [ "$host_os" = 'Linux' ]; then
  cmd="$ansible -i inventory arch.yml $roles"
else
  echo "Unknown host OS: $host_os"
  exit 1
fi

echo "##############"
echo "Running '$cmd'"
echo "##############"
sudo echo 'something' 2&>/dev/null && \
  $cmd
