#!/bin/bash
##### Prepending commit messages with JIRA ticket numbers
# Exit if not a standard commit
case "$2" in
  merge|template|squash|commit)
    exit
esac
# Exit if amending
if [ -n "$(head -n1 $1)"]; then
  exit
fi
# Include any branches for which you wish to disable this script
if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop)
fi
# Get the current branch name and check if it is excluded
BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
# Trim it down to get the parts we're interested in
TRIMMED=$(echo $BRANCH_NAME | grep -Eo "[A-Z0-9]{1,10}-?[A-Z0-9]+-\d+")
# If it isn't excluded, preprend the trimmed branch identifier to the given message
if [ -n "$BRANCH_NAME" ] \
  &&  ! [[ $BRANCH_EXCLUDED -eq 1 ]] \
  && [ ! -z $TRIMMED ]; then
  sed -i.bak -e "1s/^/$TRIMMED: /" $1
fi
