---
- name: Clone fzf repo
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    update: no

- name: Install fzf script
  shell: "~/.fzf/install"
  args:
    creates: "~/.fzf/bin/fzf"

- name: Set up temporary Vim directories
  file:
    path: '~/.local/share/nvim/{{ item }}'
    state: directory
  with_items: '{{ vim_tmp_dirs }}'

- name: Load work vars
  include_vars: work.yml
  ignore_errors: true

- name: Template dotfiles
  template: src={{ ansible_env.PWD }}/roles/dotfiles/templates/{{ item }}
        dest={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        force=yes
  with_items: '{{ templates }}'

- name: Create common dotfiles
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
        follow=false
  with_items: '{{ common_files }}'

# os specific tasks
- name: create darwin symlinks
  when: ansible_os_family == "Darwin" and darwin_files is defined
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
        follow=false
  with_items: '{{ darwin_files }}'

- name: create archlinux symlinks
  when: ansible_os_family == "Archlinux" and archlinux_files is defined
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
        follow=false
  with_items: '{{ archlinux_files }}'
