---
- name: Initialise
  include_role:
    name: initialise

- when: work
  include_vars:
    file: work.yml
    name: workvars

- name: Pull work Git repos
  when: work
  with_items: '{{ workvars.repos }}'
  git:
    repo: 'git@{{ workvars.work_git_host }}:{{ item }}'
    dest: '{{ lookup("env", "WORKPATH") }}/{{ item | basename }}'
    force: no
    update: no
