#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo "\nValidating Javascript:\n"

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m (yarn add --dev eslint)"
  exit 1
fi

PASS=true
for FILE in $STAGED_FILES
do
  "$ESLINT" "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "\t\e[4;32mESLint Passed:\e[0m $FILE"
  else
    echo "\t\e[1;4;31mESLint Failed:\e[0m $FILE"
    PASS=false
  fi
done

echo "\nESLint validation completed!\n"
if ! $PASS; then
  echo "\033[1;31mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo "\033[1;32mCOMMIT SUCCEEDED\033[0m\n"
fi
