---
- include_role:
    name: initialise

- name: Set screenshot path
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: "/Users/{{ ansible_user_id }}/Pictures/Screenshots"
    type: string
    state: present

- name: Turn off security settings
  command: spctl --master-disable
  become: true
