#!/bin/bash
set -e

SESSION=grandcentral

if tmux has-session -t $SESSION 2> /dev/null; then
  tmux attach -t $SESSION
  exit
fi

tmux new-session -d -s $SESSION -n vim

# 1. Editing
tmux send-keys -t vim "vim" Enter

# 2. Shell
tmux new-window -n term
tmux send-keys "git status" Enter

# 9. Build
tmux new-window -n build
tmux split-window -h -t $SESSION:build
tmux send-keys -t $SESSION:build.1 "npm run build:watch" Enter
tmux send-keys -t $SESSION:build.2 "docker-compose up" Enter

tmux attach -t $SESSION:vim.1
