---
- include_role:
    name: initialise

- name: Check Homebrew
  stat:
    path: /usr/local/bin/brew
  register: brew

- name: Install Homebrew
  become: true
  command: yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Brew cleanup
  command: brew cleanup
  async: 300
  poll: 15

- name: Install packages in global Brewfile (~/.Brewfile)
  command: brew bundle --global
  async: 600
  poll: 30

- include_role:
    name: yarn
