---
- name: Check Homebrew bin
  stat:
    path: /usr/local/bin/brew
  register: brew

- name: Install Homebrew
  command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Brew cleanup
  command: brew cleanup
