---
- name: Install Homebrew
  command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

- name: update Homebrew
  homebrew: update_homebrew=yes

- name: clean up old versions
  command: brew cleanup
