---
- name: pacman | upgrade
  pacman:
    upgrade: yes

- name: pacman | installing packages
  pacman: name={{ item }}
  with_items:
    - adobe-source-code-pro-fonts
    - arc-gtk-theme
    - autojump
    - clipit
    - feh
    - fzf
    - google-chrome
    - htop
    - i3blocks
    - lxappearance
    - mpv
    - mupdf
    - nerd-fonts-complete
    - pacaur
    - paper-icon-theme
    - private-internet-access-vpn
    - qbittorrent
    - ranger
    - redshift
    - ripgrep
    - rofi
    - screenfetch
    - spotify
    - tmux
    - tor-browser-en
    - ttf-font-awesome
    - ttf-inconsolata
    - ttf-roboto
    - unzip
    - vim
    - xss-lock
    - yarn
    - zsh
