---
- name: upgrade
  become: true
  pacman:
    upgrade: yes

- name: installing packages
  become: true
  pacman:
    name:
      - acpi
      - adobe-source-code-pro-fonts
      - arc-gtk-theme
      - autojump
      - connman
      - docker
      - feh
      - firefox-developer-edition
      - fzf
      - htop
      - i3-gaps
      - i3-wm
      - i3blocks
      - lxappearance
      - mpv
      - mupdf
      - qbittorrent
      - ranger
      - redshift
      - ripgrep
      - rofi
      - screenfetch
      - sudo
      - tmux
      - unzip
      - vim
      - which
      - xclip
      - xorg-server
      - xorg-xinit
      - xss-lock
      - yarn
      - zip
      - zsh

# TODO: Pacaur packages
# - clipit
# - drive
# - i3lock-fancy-git
# - nerd-fonts-complete
# - paper-icon-theme
# - spotify
# - tor-browser-en
# - nordvpn
