---
- name: pacman | upgrade
  pacman:
    upgrade: yes

- name: pacman | installing packages
  pacman: name={{ item }}
  with_items:
    - adobe-source-code-pro-fonts
    - arc-gtk-theme
    - autojump
    - connman
    - ctags
    - docker
    - feh
    - fzf
    - htop
    - i3-gaps
    - i3-wm
    - i3blocks
    - lxappearance
    - mpv
    - mupdf
    - qbittorrent
    - ranger
    - redshift
    - ripgrep
    - rofi
    - screenfetch
    - tmux
    - unzip
    - vim
    - which
    - xclip
    - xss-lock
    - yarn
    - zip
    - zsh

    # Pacaur packages
    # - clipit
    # - drive
    # - google-chrome
    # - i3lock-fancy-git
    # - nerd-fonts-complete
    # - paper-icon-theme
    # - private-internet-access-vpn
    # - spotify
    # - tor-browser-en
