---
- include_role:
    name: initialise

- name: Setup pacaur
  block:
    - name: Install git
      become: true
      pacman:
        name: git
        state: present

    - name: Setup vendor directory
      file:
        path: "{{ role_path }}/vendor"
        state: directory

    - name: Clone pacaur
      git:
        repo: "https://aur.archlinux.org/{{ item }}.git"
        dest: "{{ role_path }}/vendor/{{ item }}"
        update: no
      with_items:
        - auracle-git
        - pacaur
        - ansible-aur-git

    - name: Set up pacaur
      shell: "yes | makepkg -si"
      args:
        chdir: "{{ role_path }}/vendor/{{ item }}"
      with_items:
        - auracle-git
        - pacaur
        - ansible-aur-git

- name: Install packages
  aur:
    use: pacaur
    upgrade: no
    skip_installed: yes
    name: "{{ item }}"
  with_lines: "cat {{ role_path }}/files/pkglist.txt"
