imap jk <Esc>

let mapleader="\<Space>"
let maplocalleader="\\"

filetype indent plugin on
syntax on

" graceful degradation for plugins
if exists('&loadplugins')
  if has('packages')
     packloadall
  else
    source $HOME/.vim/pack/bundle/opt/vim-pathogen/autoload/pathogen.vim
    call pathogen#infect('pack/bundle/start/{}')
  endif
endif

" tmux split navigation
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <C-h> :TmuxNavigateLeft<CR>
nnoremap <silent> <C-j> :TmuxNavigateDown<CR>
nnoremap <silent> <C-k> :TmuxNavigateUp<CR>
nnoremap <silent> <C-l> :TmuxNavigateRight<CR>
