set encoding=UTF-8

if exists('$SUDO_USER')  " no root owned files
  set noswapfile
  set nobackup
  set nowritebackup
  set noundofile
  if has('nvim')
    set shada="NONE"
  endif
else
  " keep backup files out of the way
  set backupdir=~/.local/share/nvim/backup//
  " keep swap files out of the way
  set directory=~/.local/share/nvim/swap//
  " keep undo files out of the way
  if has('persistent_undo')
    set undodir=~/.local/share/nvim/undo//
    set undofile  " enable undo files
    set undolevels=100
  endif
endif

if !has('nvim')
  set viminfo="NONE"
endif

imap jk <Esc>

let mapleader="\<Space>"
let maplocalleader="\\"

filetype indent plugin on
syntax on

" Load local overrides ~/.vim/vimrc.local
let s:vimrc_local = $HOME . '/.vim/vimrc.local'
if filereadable(s:vimrc_local)
  execute 'source ' . s:vimrc_local
endif

" graceful degradation for plugins
if exists('&loadplugins')
  if has('packages')
     packloadall

     if !has('nvim')
       packadd markdown-preview.nvim
     endif
  else
    source $HOME/.vim/pack/bundle/opt/vim-pathogen/autoload/pathogen.vim
    call pathogen#infect('pack/bundle/start/{}')
  endif

endif

set rtp+=~/.fzf

set completeopt=menuone,noinsert,noselect
