alias g='git'
alias v='vim'
alias cl='clear'
alias dc='docker-compose'
alias killtomcat='pkill -9 -f tomcat'
alias cdp='cd $(git rev-parse --show-toplevel 2> /dev/null || echo -n ".")'
alias py='python3'
